// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/backup": {
            "get": {
                "description": "获取系统初始化时创建的顶级管理员信息",
                "produces": [
                    "application/json"
                ],
                "summary": "获取顶级管理员信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.GetAdminBackupResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/deleteAll": {
            "delete": {
                "description": "测试接口：删除所有管理员数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "删除所有管理员",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/password": {
            "get": {
                "description": "获取指定考试的管理员密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取管理员密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "考试ID",
                        "name": "examid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.GetAdminPasswordResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/update": {
            "post": {
                "description": "更新默认管理员的ID、密码和考试ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "更新管理员信息",
                "parameters": [
                    {
                        "description": "更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UpdateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exam/bind": {
            "post": {
                "description": "学生到达考场后绑定考试并获取密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "学生绑定考试",
                "parameters": [
                    {
                        "description": "绑定信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.BindStudentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.BindStudentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/exam/create": {
            "post": {
                "description": "管理员创建新的考试",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "创建新考试",
                "parameters": [
                    {
                        "description": "考试信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateExamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.CreateExamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/password": {
            "get": {
                "description": "客户端接口：获取一个未分发的考试密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取考试密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "学生ID",
                        "name": "stuid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.GetPasswordResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/validateExamPassword": {
            "post": {
                "description": "验证考试密码是否有效并返回用于后续请求的token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "考试系统登录",
                "parameters": [
                    {
                        "description": "登录验证信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ValidateExamEntryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ValidateExamEntryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.BindStudentRequest": {
            "type": "object",
            "properties": {
                "examid": {
                    "type": "string",
                    "example": "EXAM001"
                },
                "stuid": {
                    "type": "string",
                    "example": "2021001"
                }
            }
        },
        "controller.BindStudentResponse": {
            "type": "object",
            "properties": {
                "examid": {
                    "type": "string",
                    "example": "EXAM001"
                },
                "message": {
                    "type": "string",
                    "example": "绑定成功"
                },
                "password": {
                    "type": "string",
                    "example": "a1b2c3d4"
                },
                "stuid": {
                    "type": "string",
                    "example": "2021001"
                }
            }
        },
        "controller.CreateExamRequest": {
            "type": "object",
            "properties": {
                "examid": {
                    "type": "string",
                    "example": "EXAM002"
                }
            }
        },
        "controller.CreateExamResponse": {
            "type": "object",
            "properties": {
                "examid": {
                    "type": "string",
                    "example": "EXAM002"
                },
                "message": {
                    "type": "string",
                    "example": "考试创建成功"
                }
            }
        },
        "controller.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "请求参数错误"
                }
            }
        },
        "controller.GetAdminBackupResponse": {
            "type": "object",
            "properties": {
                "adminid": {
                    "type": "string",
                    "example": "admin001"
                },
                "created_at": {
                    "type": "string"
                },
                "examid": {
                    "type": "string",
                    "example": "EXAM001"
                },
                "password": {
                    "type": "string",
                    "example": "admin123456"
                }
            }
        },
        "controller.GetAdminPasswordResponse": {
            "type": "object",
            "properties": {
                "adminid": {
                    "type": "string",
                    "example": "admin001"
                },
                "examid": {
                    "type": "string",
                    "example": "EXAM001"
                },
                "password": {
                    "type": "string",
                    "example": "a1b2c3d4"
                }
            }
        },
        "controller.GetPasswordResponse": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "a1b2c3d4"
                }
            }
        },
        "controller.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "controller.UpdateAdminRequest": {
            "type": "object",
            "properties": {
                "new_adminid": {
                    "type": "string",
                    "example": "customAdmin"
                },
                "new_examid": {
                    "type": "string",
                    "example": "CUSTOM001"
                },
                "new_password": {
                    "type": "string",
                    "example": "customPassword"
                },
                "old_adminid": {
                    "type": "string",
                    "example": "admin"
                },
                "old_examid": {
                    "type": "string",
                    "example": "EXAM001"
                },
                "old_password": {
                    "type": "string",
                    "example": "admin123"
                }
            }
        },
        "controller.ValidateExamEntryRequest": {
            "type": "object",
            "properties": {
                "examid": {
                    "type": "string",
                    "example": "EXAM001"
                },
                "password": {
                    "type": "string",
                    "example": "a1b2c3d4"
                },
                "stuid": {
                    "type": "string",
                    "example": "2021001"
                }
            }
        },
        "controller.ValidateExamEntryResponse": {
            "type": "object",
            "properties": {
                "examid": {
                    "type": "string",
                    "example": "EXAM001"
                },
                "is_default": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "验证成功"
                },
                "role": {
                    "type": "string",
                    "example": "student"
                },
                "userid": {
                    "type": "string",
                    "example": "2021001"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "考试密码分发系统API",
	Description:      "提供考试密码生成、分发和验证功能的API系统",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
